version: '2'
services:
  word_book-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/word_book/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=word_book
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
